# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca49123a707219df09831acb050bd4d7d805f4bd9211860975264741bc8cb9b9d31ef0de71d2edbe46d5106abbd40dce2414dfb4adfb77d3370fd72162bb289e

test:
  secret_key_base: 72552580a914b83f3200667ae6b0f367836544f9f9289b71e4b9b382e7418c441a5d5d2c2b5bceef708047120b5499b0d33c73faa8dcd7f84eb42c194033ea8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
